// <auto-generated />
namespace Course_Management.Migrations.Security
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AuthDbScript : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AuthDbScript));
        
        string IMigrationMetadata.Id
        {
            get { return "202008111810277_AuthDbScript"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
